# Generated by Django 6.0 on 2025-12-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Kennzeichen')),
                ('brand_model', models.CharField(max_length=100, verbose_name='Hersteller & Model')),
                ('year_of_manufacture', models.IntegerField(verbose_name='Baujahr')),
                ('last_service', models.DateField(blank=True, null=True, verbose_name='Letzter Service')),
            ],
        ),
    ]
