# Generated by Django 6.0 on 2025-12-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nachname')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Führerschein-Nr.1')),
                ('license_expiry', models.DateField(verbose_name='Ablaufdatum Führerschein')),
            ],
        ),
    ]
