# Generated by Django 6.0 on 2025-12-30 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Problem (Titel)')),
                ('description', models.TextField(verbose_name='Detaillierte Beschreibung')),
                ('status', models.CharField(choices=[('new', 'Neu / Offen'), ('in_progress', 'In Bearbeitung'), ('done', 'Erledigt')], default='new', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle', verbose_name='Betroffenes Fahrzeug')),
            ],
        ),
    ]
